### PR TITLE
Scientific notation for every plot

### PR DESCRIPTION
**Pull request by RemDelaporteMathurin**
In this PR the formatting of axes ticks labels has been corrected.
Scientific notation in ensured with no offset specified.

## With a LaTEX installation
image
## Without any LaTEX installation
image

### Others
Pep8

### CODE REVIEW

**Comment by Ribodou** [comment]
I had the same result this morning when I tried to use scientific notation. I wanted to use something else because I thought that it is weird to have the exponent above the graph. If you are OK with it, I'll merge your PR.

**Comment by RemDelaporteMathurin** [comment]
Well, ask around but I usually have no problems using that notation.

**Comment by RemDelaporteMathurin** [comment]
Maybe not for the x_axis though you're right. I'll change it.

**Comment by Ribodou** [comment]
Actually, I have an issue with your PR. I tested it and I figured out that I can't plot two files anymore.
If you open json.txt twice and plot it, the program crashes.
FYI, here is the traceback:
```
  ax = self.figure.add_subplot(111)
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/matplotlib/axes/_base.py", line 2852, in ticklabel_format
    self.yaxis.major.formatter.set_scientific(sb)
AttributeError: 'LogFormatterSciNotation' object has no attribute 'set_scientific'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ribodou/remi/RD4F-Tool/src/ReadingPart.py", line 239, in on_click_tracer
    self.pltwindows[0].plot(data, legend, ylog=True, x_label="Temperature (K)", y_label=y_unit + " (logscale)")
  File "/home/ribodou/remi/RD4F-Tool/src/PltWindows.py", line 119, in plot
    ax.ticklabel_format(style='sci', scilimits=(0, 0))
  File "/usr/local/lib/python3.7/dist-packages/matplotlib/axes/_base.py", line 2875, in ticklabel_format
    "This method only works with the ScalarFormatter.")
AttributeError: This method only works with the ScalarFormatter.
[1]    17587 abort      python3 main.py
```
I'll look at it.

**Comment by RemDelaporteMathurin** [comment]
Ok, I'm able to reproduce that Error. Better close that one for now. Same is happening in #6

**Pull request closed without merging**
